# Generated by Django 6.0.4 on 2026-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscription_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video_content',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
